- name: ホストネームを設定
  hostname: name={{ hostname }}
  tags: common

- name: グループを追加
  group: name={{ user_group }}
  tags: common

- name: ユーザーを追加
  user: name={{ user_name }} group={{ user_group }}
  tags: common